### ISSUE TITLE
Power builder not working anymore Wordpress 5.6

### ISSUE THREAD

**Issue by rocko2** [templatemonster/power-builder#47]
Since update to Wordpress 5.6 Power builder stopped working.
Have installed Classic editor plugin.

Getting this error:

load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.6:formatted:1504 Uncaught TypeError: this._addClass is not a function
at t..._create (sortable.min.js?ver=1.12.1:9)
at t..._create (jquery-ui-1.10.4.custom.min.js?ver=1.4.0:6)
at t..._createWidget (jquery-ui-1.10.4.custom.min.js?ver=1.4.0:6)
at new t.. (jquery-ui-1.10.4.custom.min.js?ver=1.4.0:6)
at HTMLDivElement. (jquery-ui-1.10.4.custom.min.js?ver=1.4.0:6)
at Function.each (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.6:formatted:160)
at s.fn.init.each (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.6:formatted:78)
at s.fn.init.t.fn. [as sortable] (jquery-ui-1.10.4.custom.min.js?ver=1.4.0:6)
at Object.init (postbox.min.js?ver=5.6:2)
at Object.add_postbox_toggles (postbox.min.js?ver=5.6:2)

**Comment by LotusBluete** [comment]
I also a issue with power builder. Nothing helped but downgrading to Version WP 5.5., which solved the issue - well for now. We are planning to rebuild the site and change the theme now (and not using Template Monster again). 

Please let me know if downgrading is also helping you and how you plan to deal with the problem.

**Comment by giuliopons** [comment]
Instead of downgrading WP, another solution is installing "jQuery Migrate Helper" plugin. It allows to force Wordpress to use the previous version of jQuery.
Install plugin.
Go to plugin settings (the link is in the admin bar).
Choose Legacy 1.12.4-wp
Maybe this workaround has side-effects.

**Comment by khaynik** [comment]
When I updated Wordpress to 5.6.1 now the Power Builder does not show on each of my pages to use. Any solutions other than the "jQuery Migrate Helper" plugin since this is a temporary fix?

Seems like the JQuery is not updated on Power Builder.

**Comment by ADVMOSCA** [comment]
Hi, would you be kind enough to confirm update on power builder?
Thanks

**Comment by berndgassmann** [comment]
Hi,
I've found another workaround for this issue. The reason is that power builder comes with 
power-builder/framework/admin/assets/js/libs/jquery-ui-1.10.4.custom.min.js
and the new WP jquery code tries to call _addClass and _removeClass functions, which were added in later versions of jquiery-ui and therefore the Exception is raised and the following code is not executed.
Therefore, I've replaced:
`_create:t.noop,_init:t.noop,`
with
`_create:t.noop,_addClass:t.noop,_removeClass:t.noop,_init:t.noop,`
 in the file, so that the exception is gone and it seems to me as if it's working for now.

The proper way out of this problem is for sure to migrate power builder to a more recent version of jquery ui...

**Comment by micahlt** [comment]
Same issue here - however, it appears that replacing that line of code doesn't fix the problem anymore.  Still getting the same console error.  I'm not expecting a fix anytime soon either, since it appears that the most recent commit is from 2017.

**Comment by nathanielwarner** [comment]
The solution provided by @berndgassmann continues to work for me!
